#  Template NodeJS Web Application for Azure Web App service

#  This template allows you to deploy your NodeJS web application to Azure Web App Service.
#  The workflow allows running tests, code linting and security scans on feature branches (as well as master).
#  The NodeJS application will be validated after the code is merged to master and deployment can be triggered manually.

# Prerequisites: $$AZURE_APP_ID, $AZURE_PASSWORD, $AZURE_TENANT_ID, $AZURE_RESOURCE_GROUP, $AZURE_APP_NAME setup in the Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/microsoft/azure-web-apps-deploy/src/1.0.3/README.md

image: node:16

pipelines:
  # Triggered for all other branches except those explicitly defined below
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm ci
              - npm test
        - step:
            name: Code linting
            script:
              - npm ci eslint
              - npx eslint .
            caches:
              - node
  branches:
    # Deploys to Azure "DevTest" environment,
    # which corresponds to BitBucket "Test" deployment environment
    # https://support.atlassian.com/bitbucket-cloud/docs/set-up-and-monitor-deployments/#Step-1--Define-your-environments
    dev:
      - stage:
          name: 'Build, Test & Deploy to AZ DevTest environment'
          deployment: Test 
          steps: 
            - step:
                name: Build and Test
                caches:
                  - node
                script:
                  - npm ci
                  - npm test
                  - npm run build
                artifacts:
                  - dist/**
            - step:
                name: Deploy to DevTest
                script:
                  - pipe: atlassian/azure-storage-deploy:1.1.0
                    variables:
                      SOURCE: dist
                      DESTINATION: https://${AZURE_STORAGE_ACCOUNT}.blob.core.windows.net/%24web/?
                      DESTINATION_SAS_TOKEN: ${DESTINATION_SAS_TOKEN}
                      EXTRA_ARGS: "--as-subdir=false"
                      DEBUG: "true" # Optional.
